dist: trusty
language: node_js
node_js:
  - 6
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - pulseaudio
cache:
  directories:
    - node_modules

env:
  global:
    - CXX=g++-4.8
  matrix:
    - BROWSER=chrome  BVER=stable

before_script:
  - ./node_modules/travis-multirunner/setup.sh
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - pulseaudio --start

script:
  - npm run test-travis

after_failure:
  - for file in *.log; do echo $file; echo "======================"; cat $file; done || true

notifications:
  email:
  - 
